const landing=document.querySelector('#landing'),game=document.querySelector('#game'),canvas=document.querySelector('#map'),ctx=canvas.getContext('2d');let player={x:0,y:250},car={x:0,y:80},driving=false,keys={},touch={x:0,y:0};
const roads=[{x:-30,y:0,w:60,h:500},{x:-250,y:205,w:500,h:56},{x:-10,y:0,w:20,h:500},{x:-250,y:90,w:500,h:18}];const buildings=[[-190,20,105,120], [65,20,120,120],[-190,290,105,150],[65,290,120,150],[-220,130,70,55],[150,130,70,55],[-140,330,75,80],[65,330,75,80]];
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function worldToScreen(x,y){return{x:innerWidth/2+x,y:innerHeight/2+y-80}}
function draw(){ctx.fillStyle='#9cbea7';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(innerWidth/2,innerHeight/2-80);ctx.translate(-player.x,-player.y);ctx.fillStyle='#33434a';roads.forEach(r=>ctx.fillRect(r.x,r.y,r.w,r.h));ctx.strokeStyle='#efb84b88';ctx.setLineDash([12,12]);ctx.lineWidth=2;roads.slice(0,3).forEach(r=>{if(r.w>r.h){ctx.beginPath();ctx.moveTo(r.x,r.y+r.h/2);ctx.lineTo(r.x+r.w,r.y+r.h/2)}else{ctx.beginPath();ctx.moveTo(r.x+r.w/2,r.y);ctx.lineTo(r.x+r.w/2,r.y+r.h)}ctx.stroke()});ctx.setLineDash([]);buildings.forEach((b,i)=>{ctx.fillStyle=i%3?'#b86f52':'#d2a45b';ctx.fillRect(...b);ctx.fillStyle='#f6db9a';for(let wx=b[0]+12;wx<b[0]+b[2]-8;wx+=22)for(let wy=b[1]+12;wy<b[1]+b[3]-8;wy+=24)ctx.fillRect(wx,wy,7,9)});ctx.fillStyle='#d94e45';ctx.fillRect(car.x-10,car.y-19,20,38);ctx.fillStyle='#f5d6a1';ctx.fillRect(car.x-7,car.y-12,14,9);ctx.fillStyle='#efb84b';ctx.beginPath();ctx.arc(player.x,player.y,10,0,Math.PI*2);ctx.fill();ctx.restore();requestAnimationFrame(draw)}
function tick(){let dx=touch.x||(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=touch.y||(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(driving){car.x+=dx*2.8;car.y+=dy*2.8;player.x=car.x;player.y=car.y}else{player.x+=dx*2.4;player.y+=dy*2.4}requestAnimationFrame(tick)}
function showGame(){landing.hidden=true;game.hidden=false;draw();tick()}document.querySelector('#launch').onclick=showGame;document.querySelector('#back').onclick=()=>{game.hidden=true;landing.hidden=false};document.querySelector('#reset').onclick=()=>{player={x:0,y:250};car={x:0,y:80};driving=false};document.querySelector('#drive').onclick=()=>{if(Math.hypot(player.x-car.x,player.y-car.y)<55||driving){driving=!driving;document.querySelector('#drive').textContent=driving?'GET OUT':'GET IN CAR';document.querySelector('#mode').textContent=driving?'DRIVING':'ON FOOT'}};addEventListener('keydown',e=>keys[e.key]=true);addEventListener('keyup',e=>keys[e.key]=false);
const joy=document.querySelector('#joystick'),stick=joy.querySelector('.stick');function move(e){const r=joy.getBoundingClientRect(),p=e.touches?e.touches[0]:e,x=Math.max(-1,Math.min(1,(p.clientX-(r.left+r.width/2))/42)),y=Math.max(-1,Math.min(1,(p.clientY-(r.top+r.height/2))/42));touch={x,y};stick.style.transform=`translate(${x*30}px,${y*30}px)`}['touchstart','touchmove'].forEach(n=>joy.addEventListener(n,e=>{e.preventDefault();move(e)}));['touchend','touchcancel'].forEach(n=>joy.addEventListener(n,()=>{touch={x:0,y:0};stick.style.transform=''}));
let promptEvent;addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;document.querySelector('#install').hidden=false});document.querySelector('#install').onclick=async()=>{if(promptEvent){promptEvent.prompt();promptEvent=null}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=4').catch(()=>{});if(location.search.includes('play=1')||location.hash==='#prototype')showGame();
